# Generated by Django 5.0.2 on 2024-04-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srno', models.CharField(max_length=100)),
                ('album_title', models.CharField(max_length=100)),
                ('album_artist', models.CharField(max_length=100)),
                ('album_genre', models.CharField(max_length=100)),
                ('album_relese_year', models.CharField(max_length=100)),
                ('song_title', models.CharField(max_length=100)),
                ('song_artist', models.CharField(max_length=100)),
                ('song_genre', models.CharField(max_length=100)),
                ('song_relese_year', models.CharField(max_length=100)),
            ],
        ),
    ]
